/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package graficas;

import dto.Operaciones;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JOptionPane;
import logica.GestionDeTarjeta;
import dto.CrearTarjeta;
import dto.Opciones;
import dto.OpcionesTipoDocu;
import java.text.DateFormat;
import java.util.ArrayList;
import java.util.Map;
import javax.swing.table.DefaultTableModel;
import utilidades.GArchivos;




/**
*
 * @author pipet
 */
public class VentanaAdministracion extends javax.swing.JFrame {
    private Opciones opcion;
    private OpcionesTipoDocu opcion1;
    public int cupoVal = 0;
    //private DefaultTableModel modelTabla;
    DefaultTableModel tableModel  = new DefaultTableModel();
    ArrayList<CrearTarjeta> listaTarjeta = new ArrayList<CrearTarjeta>();
    /**
     * Creates new form VentanaCreacionTarjeta
     */
    public VentanaAdministracion() {
        initComponents();
        tableModel.addColumn("Nombre");
        tableModel.addColumn("Num T.");
        tableModel.addColumn("Tipo I.");
        tableModel.addColumn("Num I.");
        tableModel.addColumn("Tipo T.");
        tableModel.addColumn("Fecha C.");
//        String[] titulo= new String[]{"Num T.", "Nombre", "Tipo I.", "Num I.", "Tipo T.", "Fecha C."};
//        tableModel.setColumnIdentifiers(titulo);
        this.cargarTarjetas();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupoBotones = new javax.swing.ButtonGroup();
        grupoBotones2 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cjNombre = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        cjIdenti = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        cjSalario = new javax.swing.JTextField();
        bCreacionTarjeta = new javax.swing.JButton();
        cjSalir = new javax.swing.JButton();
        bCompra = new javax.swing.JButton();
        bPago = new javax.swing.JButton();
        bMaster = new javax.swing.JRadioButton();
        bVisa = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        bCedula = new javax.swing.JRadioButton();
        bTIdentidad = new javax.swing.JRadioButton();
        bOtro = new javax.swing.JRadioButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTabla = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setText("Sistema de Administracion de Tarjeta de Credito");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(230, 10, 340, 16);

        jLabel2.setText("Nombre completo del titular: ");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 50, 170, 16);
        getContentPane().add(cjNombre);
        cjNombre.setBounds(180, 50, 540, 22);

        jLabel3.setText("Numero de Identificación: ");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(10, 90, 200, 16);
        getContentPane().add(cjIdenti);
        cjIdenti.setBounds(390, 90, 330, 22);

        jLabel4.setText("Salario del Titular");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(10, 140, 110, 10);
        getContentPane().add(cjSalario);
        cjSalario.setBounds(140, 140, 250, 30);

        bCreacionTarjeta.setText("Crear Tarjeta ");
        bCreacionTarjeta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCreacionTarjetaActionPerformed(evt);
            }
        });
        getContentPane().add(bCreacionTarjeta);
        bCreacionTarjeta.setBounds(480, 130, 170, 25);

        cjSalir.setText("Salir");
        cjSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cjSalirActionPerformed(evt);
            }
        });
        getContentPane().add(cjSalir);
        cjSalir.setBounds(640, 10, 80, 25);

        bCompra.setText("Realizar Compra");
        bCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCompraActionPerformed(evt);
            }
        });
        getContentPane().add(bCompra);
        bCompra.setBounds(480, 170, 170, 25);

        bPago.setText("Pago Tarjeta");
        bPago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bPagoActionPerformed(evt);
            }
        });
        getContentPane().add(bPago);
        bPago.setBounds(480, 210, 170, 25);

        grupoBotones.add(bMaster);
        bMaster.setText("MASTERCARD");
        bMaster.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bMasterActionPerformed(evt);
            }
        });
        getContentPane().add(bMaster);
        bMaster.setBounds(290, 190, 220, 25);

        grupoBotones.add(bVisa);
        bVisa.setText("VISA");
        bVisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bVisaActionPerformed(evt);
            }
        });
        getContentPane().add(bVisa);
        bVisa.setBounds(290, 220, 240, 25);

        jLabel5.setText("Seleccione el tipo de tarjeta que desea");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(50, 190, 230, 16);

        jLabel6.setText("solicitar");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(50, 210, 120, 16);

        grupoBotones2.add(bCedula);
        bCedula.setText("C.C.");
        bCedula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCedulaActionPerformed(evt);
            }
        });
        getContentPane().add(bCedula);
        bCedula.setBounds(180, 90, 70, 25);

        grupoBotones2.add(bTIdentidad);
        bTIdentidad.setText("T.I.");
        bTIdentidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bTIdentidadActionPerformed(evt);
            }
        });
        getContentPane().add(bTIdentidad);
        bTIdentidad.setBounds(250, 90, 50, 25);

        grupoBotones2.add(bOtro);
        bOtro.setText("Otro");
        bOtro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bOtroActionPerformed(evt);
            }
        });
        getContentPane().add(bOtro);
        bOtro.setBounds(310, 90, 70, 25);

        jTabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5"
            }
        ));
        jScrollPane2.setViewportView(jTabla);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(20, 260, 690, 120);

        jLabel7.setText("(sin puntos ni comas)");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(10, 150, 120, 20);

        setSize(new java.awt.Dimension(748, 445));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cjSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cjSalirActionPerformed
       System.exit(0);
    }//GEN-LAST:event_cjSalirActionPerformed

    private void bCreacionTarjetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCreacionTarjetaActionPerformed
        this.CrearTarjeta();
    }//GEN-LAST:event_bCreacionTarjetaActionPerformed

    private void bCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCompraActionPerformed
        this.compra();
    }//GEN-LAST:event_bCompraActionPerformed

    private void bPagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bPagoActionPerformed
       this.pagoTarjeta();
    }//GEN-LAST:event_bPagoActionPerformed

    private void bMasterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bMasterActionPerformed
       this.clickOpcion(1);
    }//GEN-LAST:event_bMasterActionPerformed

    private void bVisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bVisaActionPerformed
       this.clickOpcion(2);
    }//GEN-LAST:event_bVisaActionPerformed

    private void bCedulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCedulaActionPerformed
       this.clickOpcionDocu(1);
    }//GEN-LAST:event_bCedulaActionPerformed

    private void bTIdentidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bTIdentidadActionPerformed
       this.clickOpcionDocu(2);
    }//GEN-LAST:event_bTIdentidadActionPerformed

    private void bOtroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bOtroActionPerformed
       this.clickOpcionDocu(3);
    }//GEN-LAST:event_bOtroActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaAdministracion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaAdministracion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaAdministracion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaAdministracion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaAdministracion().setVisible(true);
            }
        });
    }//FIN MAIN
    
    static final ArrayList listaTarjetas = new ArrayList();
    
    private void clickOpcion(int opcion){
        //JOptionPane.showMessageDialog(this, opcion);
        if (opcion == 1){
            this.opcion = Opciones.MASTERCARD;
        }else{
            this.opcion = Opciones.VISA;
        }
    }
    
     private void clickOpcionDocu(int opcion1){
        //JOptionPane.showMessageDialog(this, opcion);
        if (opcion1 == 1){
            this.opcion1 = OpcionesTipoDocu.CC;
        }else if(opcion1 == 2){
            this.opcion1 = OpcionesTipoDocu.TI;
        }else{
            this.opcion1 = OpcionesTipoDocu.Otro;
        }
    }
    
    public void CrearTarjeta(){
     
        String nombre = cjNombre.getText();
        String identi = cjIdenti.getText();
        String salarioS = cjSalario.getText();
        
        if(nombre.isEmpty() || identi.isEmpty() || salarioS.isEmpty()){
            JOptionPane.showMessageDialog(null, "Campos Vacios o Datos no Validos");
        }else{
        
          //Fecha de Creacion
          Calendar calendar = Calendar.getInstance();
          Date fechaCreaci = calendar.getTime();
          
          
          //Numeros de la tarjeta
          Operaciones ope = new Operaciones();
          String numTarjeta = ope.NumerosTar();
        
          //Cupo de la tarjeta
          Integer salario;
          if(salarioS == null){
              salario=0;
          }else{
              salario = Integer.parseInt(salarioS);
          }
          cupoVal = ope.CalculoCupo(salario);
          ope.setCupo(cupoVal);
          
          if(this.opcion1 == null){
              JOptionPane.showMessageDialog(null, "Elija el tipo de documento");
          }else{
               if(this.opcion == null){
              JOptionPane.showMessageDialog(null, "Elija el tipo de tarjeta");
          }else{
          //Creacion de la Tarjeta
         GestionDeTarjeta gt = new GestionDeTarjeta();
         CrearTarjeta ct = gt.crearTarjetaCredito(nombre, identi, numTarjeta, cupoVal, fechaCreaci, this.opcion, this.opcion1);
         listaTarjeta.add(ct);
         if (ct != null){
             this.cargarTarjetas();
             String arch = ("-------------------------\n"+"Titular: "+ct.getTarjeta().getTitular()+"\n"+"Identificacion: "+ct.getTarjeta().getIdenti()+"\n"+"Tipo de Documento: "+ct.getOpcionDocu()+"\n"+"Numero de Tarjeta: "+ct.getNumTarjeta()+"\n"+"Cupo generado: "+cupoVal+"\n"+"Fecha de creacion: "+util.Util.convertirDateString(ct.getFechaCrea())+"\n"+"Tipo de Tarjeta: "+ct.getOpcion()+"\n"+"-------------------------");
             ope.guardarArchivoPlano(arch);
             //listaTarjetas.add(ct);
             //boolean b = utilidades.GArchivos.guardar("listaTarjetas.txt", listaTarjetas);
             JOptionPane.showMessageDialog(this, "Creo la tarjeta: \n "+ct+" ");
             cargarTarjetas();
         }else{
            JOptionPane.showMessageDialog(this, "No se creo la tarjeta");
            }
         }
        }
       }
       
        
    }
    
    
    public void pagoTarjeta(){
        Operaciones op = new Operaciones();
        String pagoVar = JOptionPane.showInputDialog("Ingrese el valor que pagara a la tarjeta");
        if(pagoVar == null){
            JOptionPane.showMessageDialog(null, "No se puede proceder con el pago");
        }else{
        int pago= Integer.parseInt(pagoVar);
        if(pago < 0){
            JOptionPane.showMessageDialog(null, " No se puede proceder con el pago, valor no valido");
        }else{
            
        //int cupoTar= op.obtCupo();
        String resultPag= op.pago(pago, cupoVal);
        op.setCupo(Integer.parseInt(resultPag));
        cupoVal = op.getCupo();
        JOptionPane.showMessageDialog(null, "Se pago la tarjeta con: "+pago+"\n El nuevo valor del"
                +" cupo de la tarjeta es de: "+cupoVal);
        }
       }
    }
    
        //a
        
    public void compra(){
       Operaciones op = new Operaciones();
       String compraVar = JOptionPane.showInputDialog("El valor del cupo es de: "+cupoVal+"\nIngrese el valor de la compra");
       if(compraVar == null){
            JOptionPane.showMessageDialog(null, "No se puede proceder con la compra");
        }else{
       int compra= Integer.parseInt(compraVar);
       //int cupoTar= op.obtCupo();
       if(compra == 0 || compra > cupoVal || compra < 0){
           JOptionPane.showMessageDialog(null, "No se puede proceder con la compra, valor no valido");
       }else{
       op.setValCompra(compra);
       String resultComp = op.compra(compra, cupoVal);
       op.setCupo(Integer.parseInt(resultComp));
       cupoVal = op.getCupo();
       JOptionPane.showMessageDialog(null, "El valor de la compra realizada fue de: "+String.valueOf(compra) 
              + "\n El cupo actual de la tarjeta es de: "+op.getCupo());
       
      }
     }
    }
    
    
    private void cargarTarjetas(){
        while(tableModel.getRowCount()>0){
            tableModel.removeRow(0);
        }
        
        
        for (CrearTarjeta ct: listaTarjeta) {
            Object a[] = new Object[6];
            a[0]= ct.getTarjeta().getTitular();
            a[1]= ct.getNumTarjeta();
            a[2]= ct.getOpcionDocu();
            a[3]= ct.getTarjeta().getIdenti();
            a[4]= ct.getOpcion();
            a[5]= util.Util.convertirDateString(ct.getFechaCrea());
            tableModel.addRow(a);
            
        }
      jTabla.setModel(tableModel);
    }
    
//    private void cargarTarjetas(){
//        DefaultTableModel modelo = new DefaultTableModel();
//        modelo.addColumn("Num T.");
//        modelo.addColumn("Nombre");
//        modelo.addColumn("Tipo I.");
//        modelo.addColumn("Numero I.");
//        modelo.addColumn("Tipo T.");
//        modelo.addColumn("Fecha Creacion");
//        
//         GestionDeTarjeta gestor = new GestionDeTarjeta();
//        Map<String, CrearTarjeta> lista = gestor.obtenerLista();
//        for (Map.Entry<String, CrearTarjeta> dato  : lista.entrySet()) {
//            CrearTarjeta latarjeta = dato.getValue();
//            Object[] datos = {
//                latarjeta.getNumTarjeta(),
//          
//                latarjeta.getTarjeta().getTitular(),
//                latarjeta.getOpcionDocu().toString(),
//                latarjeta.getTarjeta().getIdenti(),
//                latarjeta.getOpcion().toString(),
//                util.Util.convertirDateString(latarjeta.getFechaCrea())
//            };
//            modelo.addRow(datos);
//            
//        }
//        this.jTabla.setModel(modelo);
//         
//    }
    
   
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton bCedula;
    private javax.swing.JButton bCompra;
    private javax.swing.JButton bCreacionTarjeta;
    private javax.swing.JRadioButton bMaster;
    private javax.swing.JRadioButton bOtro;
    private javax.swing.JButton bPago;
    private javax.swing.JRadioButton bTIdentidad;
    private javax.swing.JRadioButton bVisa;
    private javax.swing.JTextField cjIdenti;
    private javax.swing.JTextField cjNombre;
    private javax.swing.JTextField cjSalario;
    private javax.swing.JButton cjSalir;
    private javax.swing.ButtonGroup grupoBotones;
    private javax.swing.ButtonGroup grupoBotones2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTabla;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
